version: "3.8"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: twitter-bot-redis
    restart: always
    networks:
      - chatbot

  chatbot:
    build: .
    container_name: twitter-bot
    depends_on:
      - redis
      - postgres
    environment:
      AGENT_PACK_PATH: ${AGENT_PACK_PATH}
      APP_PORT: ${APP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      VECTOR_STORE: ${VECTOR_STORE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE}
      OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS}
      AGENT_MEMORY_BACKEND: ${AGENT_MEMORY_BACKEND}
      REDIS_URL: ${REDIS_URL}
      AGENT_MEMORY_WINDOW: ${AGENT_MEMORY_WINDOW}
      LLM_PROVIDER: ${LLM_PROVIDER}
      OPENAI_MODEL: ${OPENAI_MODEL}
      RAG_PROVIDER: ${RAG_PROVIDER}
      RAG_DOCS_PATH: ${RAG_DOCS_PATH}
      RAG_REMOTE_URLS: ${RAG_REMOTE_URLS}
      VECTOR_INDEX_NAME: ${VECTOR_INDEX_NAME}
      AGENT_PROMPT: ${AGENT_PROMPT}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      LLM_TOOLS_CONFIG: ${LLM_TOOLS_CONFIG}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      CREDENTIAL_DEFINITION_ID: ${CREDENTIAL_DEFINITION_ID}
      VS_AGENT_ADMIN_URL: ${VS_AGENT_ADMIN_URL}
      VS_AGENT_STATS_ENABLED: ${VS_AGENT_STATS_ENABLED}
      TWITTER_APP_KEY: ${TWITTER_APP_KEY}
      TWITTER_APP_SECRET: ${TWITTER_APP_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
      TWITTER_HANDLE: ${TWITTER_HANDLE}
      DAILY_POST_BUDGET: ${DAILY_POST_BUDGET}
    volumes:
      - ./docs:/app/rag/docs
      - ./agent-packs:/app/agent-packs
    networks:
      - chatbot

  vs-agent:
    image: io2060/vs-agent:v1.5.5
    container_name: twitter-bot-vs-agent
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - chatbot
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      AGENT_ENDPOINT: ${AGENT_ENDPOINT}
      AGENT_INVITATION_IMAGE_URL: ${AGENT_INVITATION_IMAGE_URL}
      AGENT_LABEL: ${AGENT_LABEL}
      ANONCREDS_SERVICE_BASE_URL: ${ANONCREDS_SERVICE_BASE_URL}
      USE_CORS: ${USE_CORS}
      EVENTS_BASE_URL: ${EVENTS_BASE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AGENT_INVITATION_BASE_URL: ${AGENT_INVITATION_BASE_URL}
      REDIS_HOST: ${REDIS_HOST}

  postgres:
    image: postgres:alpine3.19
    container_name: twitter-bot-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - chatbot

volumes:
  postgres_data:

networks:
  chatbot:
    driver: bridge
